import React from 'react';
import { X, Printer, Download, Flame, ShieldAlert, FileText, CheckCircle2 } from 'lucide-react';
import jsPDF from 'jspdf';

export default function DirectiveModal({ incident, onClose }) {
  if (!incident) return null;

  const downloadPDF = () => {
    const doc = new jsPDF();

    // PDF Title Header
    doc.setFillColor(15, 23, 42); // slate dark background
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(245, 158, 11); // Amber
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('OIL INDIA LIMITED - HSE DIRECTIVE', 15, 18);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('SIF PRECURSOR EMERGENCY DIRECTIVE & ACTION DIRECTIVE', 15, 28);
    doc.text(`Ref: ${incident.id || 'OIL-DIRECTIVE-2026'} | Issued: ${incident.date || new Date().toISOString().split('T')[0]}`, 15, 34);

    // Alert Status
    doc.setFillColor(239, 68, 68);
    doc.rect(15, 48, 180, 12, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`ALERT: ${incident.severityLevel || 'CRITICAL SIF PRECURSOR'} (${incident.sifProbability || 85}% SIF RISK)`, 20, 56);

    // Section 1: Facility & Location
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Operational Facility & Location Details', 15, 72);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Facility / Site: ${incident.facility || 'Duliajan Drilling Rig #4'}`, 15, 80);
    doc.text(`Report Type: ${incident.reportType || 'Unsafe Act'}`, 15, 86);
    doc.text(`Primary Hazard: ${incident.rootCause || 'Work at Height / High Energy'}`, 15, 92);

    // Section 2: Description
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('2. Safety Incident Description (NLP Processed)', 15, 106);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const splitDesc = doc.splitTextToSize(incident.description || 'Description unavailable', 180);
    doc.text(splitDesc, 15, 114);

    let yPos = 114 + (splitDesc.length * 6) + 10;

    // Section 3: Mitigations
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('3. Mandatory HSE Corrective Actions & IOGP Directives', 15, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    if (incident.mitigations && incident.mitigations.length > 0) {
      incident.mitigations.forEach((m, idx) => {
        const splitMitigation = doc.splitTextToSize(`${idx + 1}. ${m}`, 175);
        doc.text(splitMitigation, 18, yPos);
        yPos += splitMitigation.length * 6 + 2;
      });
    } else {
      doc.text('Standard safety protocol compliance required.', 18, yPos);
      yPos += 10;
    }

    yPos += 15;
    doc.setDrawColor(203, 213, 225);
    doc.line(15, yPos, 195, yPos);
    yPos += 10;

    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text('Authorized by Oil India Limited HSE Directorate • Generated by AI/NLP SIF Engine (SIH26165)', 15, yPos);

    doc.save(`OIL_SIF_Directive_${incident.id || 'Report'}.pdf`);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="glass-panel w-full max-w-3xl border-red-500/40 glow-sif overflow-hidden my-8">
        {/* Modal Header */}
        <div className="bg-slate-900 px-6 py-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-red-500/20 text-red-400">
              <ShieldAlert className="w-5 h-5 animate-pulse" />
            </div>
            <div>
              <h3 className="font-extrabold text-white text-base">OIL SIF PRECURSOR SAFETY DIRECTIVE</h3>
              <span className="text-xs text-slate-400 font-mono">Incident Ref: {incident.id}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button onClick={downloadPDF} className="btn-primary text-xs">
              <Download className="w-4 h-4" /> Download PDF Directive
            </button>
            <button onClick={onClose} className="p-2 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body - Printable Layout */}
        <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto font-sans text-slate-200">
          {/* Header Banner */}
          <div className="bg-gradient-to-r from-red-950/60 via-slate-900 to-red-950/60 p-4 rounded-xl border border-red-500/30 flex items-center justify-between">
            <div>
              <span className="text-[10px] uppercase font-bold text-red-400 tracking-wider">OFFICIAL DIRECTIVE LEVEL</span>
              <div className="text-lg font-extrabold text-white flex items-center gap-2 mt-0.5">
                <span>{incident.severityLevel || 'CRITICAL SIF PRECURSOR'}</span>
              </div>
            </div>
            <div className="text-right">
              <div className="text-2xl font-extrabold font-mono text-red-400">{incident.sifProbability}%</div>
              <div className="text-[10px] text-slate-400">SIF RISK INDEX</div>
            </div>
          </div>

          {/* Details Table */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs bg-slate-900/90 p-4 rounded-xl border border-slate-800">
            <div>
              <span className="text-[10px] text-slate-400 block font-semibold">Operational Site</span>
              <span className="font-bold text-white">{incident.facility}</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 block font-semibold">Report Category</span>
              <span className="font-bold text-amber-400">{incident.reportType}</span>
            </div>
            <div>
              <span className="text-[10px] text-slate-400 block font-semibold">Root Cause Category</span>
              <span className="font-bold text-cyan-400">{incident.rootCause}</span>
            </div>
          </div>

          {/* Incident Description */}
          <div>
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Original Incident Text (NLP Processed)</h4>
            <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 text-xs font-mono leading-relaxed text-slate-300">
              "{incident.description}"
            </div>
          </div>

          {/* High Energy & Missing Safeguards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-slate-900/90 p-3.5 rounded-xl border border-slate-800">
              <h5 className="text-xs font-bold text-amber-400 flex items-center gap-1.5 mb-2">
                <Flame className="w-4 h-4" /> Detected High Energy Exposures
              </h5>
              <div className="flex flex-wrap gap-1.5">
                {incident.detectedEnergies && incident.detectedEnergies.map(e => (
                  <span key={e.id} className="badge badge-amber text-[10px]">
                    ⚡ {e.label}
                  </span>
                ))}
              </div>
            </div>

            <div className="bg-slate-900/90 p-3.5 rounded-xl border border-slate-800">
              <h5 className="text-xs font-bold text-red-400 flex items-center gap-1.5 mb-2">
                <ShieldAlert className="w-4 h-4" /> Critical Control Omissions
              </h5>
              <div className="flex flex-wrap gap-1.5">
                {incident.missingControls && incident.missingControls.map((c, i) => (
                  <span key={i} className="badge badge-sif text-[10px]">
                    🛑 {c}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Corrective Actions */}
          <div>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2 flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-cyan-400" /> Mandatory Field Corrective Actions
            </h4>
            <div className="space-y-2">
              {incident.mitigations && incident.mitigations.map((action, i) => (
                <div key={i} className="bg-slate-900 p-3 rounded-lg border border-slate-800 text-xs text-slate-200 flex items-start gap-2.5">
                  <span className="font-bold text-cyan-400 font-mono">{i + 1}.</span>
                  <span>{action}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="bg-slate-900 px-6 py-3 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
          <span>Oil India Limited HSSE Safety Directorate</span>
          <button onClick={onClose} className="btn-secondary text-xs">Close Preview</button>
        </div>
      </div>
    </div>
  );
}
